Class {
	#name : #FmxSQLQEntity,
	#superclass : #MooseEntity,
	#category : #'FamixSQLQuery-Model-Entities'
}

{ #category : #meta }
FmxSQLQEntity class >> annotation [

	<FMClass: #Entity super: #MooseEntity>
	<package: #'FamixSQLQuery-Model'>
	<generated>
	^self
]

{ #category : #meta }
FmxSQLQEntity class >> metamodel [

	<generated>
	^ FmxSQLQModel metamodel
]

{ #category : #testing }
FmxSQLQEntity >> isAccess [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isAlias [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isAliasAccess [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isAssociation [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isCursor [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isEntitySourceAnchor [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isExceptClause [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isFromClause [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isGroupByClause [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isHavingClause [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isIntersectClause [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isInvocation [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isJoinClause [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isLimitClause [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isLocalVariable [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isLocalVariableAccess [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isOnConflictClause [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isOrderByClause [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isParameterAccess [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isReturningClause [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isSelectClause [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isSetClause [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isStoredProcedure [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isStoredProcedureCall [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isStructuralEntity [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isTriggerStoredProcedure [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isUnionClause [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isUsingClause [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isValuesClause [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isView [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isWhereClause [

	<generated>
	^ false
]

{ #category : #testing }
FmxSQLQEntity >> isWithClause [

	<generated>
	^ false
]
