Class {
	#name : #FamixSQLColumnContainerReference,
	#superclass : #FamixSQLEntity,
	#traits : 'FamixSQLTColumnContainerReference',
	#classTraits : 'FamixSQLTColumnContainerReference classTrait',
	#category : #'SQL-Model-Entities'
}

{ #category : #meta }
FamixSQLColumnContainerReference class >> annotation [

	<FMClass: #ColumnContainerReference super: #FamixSQLEntity>
	<package: #'SQL-Model'>
	<generated>
	^ self
]
